Repository Phoenix-Games-Revolution/ls-design, pull requests merged in 2025-04, with the labels that each got.

#49 docs(paleodor-antagonist): antagonist aniquity
  docs/script/characters/antiquity/main_characters/paleodor_antagonist/appearance-paleodor.md
  docs/script/characters/antiquity/main_characters/paleodor_antagonist/background-paleodor.md
  docs/script/characters/antiquity/main_characters/paleodor_antagonist/speech-paleodor.md
Labels: documentation

#44 docs(kastor-protagonist): protagonist - appearance
  docs/script/characters/antiquity/main_characters/kastor-protagonist/appearance-kastor.md
  docs/script/characters/antiquity/main_characters/kastor-protagonist/background-kastor.md
  docs/script/characters/antiquity/main_characters/kastor-protagonist/speech-kastor.md
Labels: documentation

#61 docs(docs): new template
  .github/ISSUE_TEMPLATE/docs.yml
Labels: enhancement

#63 docs(gameplay-concept): gameplay concept
  docs/gdd/overview/gameplay-concept.md
Labels: documentation

#65 Feat/docs template
  .github/ISSUE_TEMPLATE/docs.yml
Labels: bug
